### ISSUE TITLE
mui < v5 is imported instead of mui > v5

### ISSUE THREAD

**Issue by AnnoDomine** [Phrensoua/mui-phone-number#1]
Inside the index.d.ts (in mui-phone-number) the TextFieldProps are wrong imported for mui > v5

The import is from "@material-ui/core"
should be: `import { TextFieldProps } from "@mui/material";`

**Comment by Morriz** [comment]
is this released? I see old styling

**Comment by Phrensoua** [comment]
@Morriz indeed I did a bad publish. sorry about that. I had published 2.2.11 but not fully tested, let me know if you have issues...

**Comment by Morriz** [comment]
I switched to `mui-tel-number` instead which looks better
